### ISSUE TITLE
overall stats

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#113]
make switch to live stats update on home page.

**Comment by dalekunce** [comment]
@kamicut what is the status of this?

**Comment by smit1678** [comment]
@dalekunce - Since we don't have historical data back to 2014, I'm thinking of the following for a near term solution: 

  - deploy total stats on the API https://github.com/AmericanRedCross/osm-stats-api/pull/7
  - add code to the frontend to pull these stats
  - then add logic to increase the total by a certain number to get to 2014 numbers

Otherwise we just show live stats from from the day we started tracking.
