### ISSUE TITLE
gps traces missing from profile

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#140]
how do GPS trace upload stats get pulled in? do they need to be hashtagged in the title or tagged with a particular keyword?
![screen shot 2016-03-06 at 12 35 54 pm](https://cloud.githubusercontent.com/assets/4806884/13555812/05a10ece-e398-11e5-9c9f-6720042bfbea.png)
but...
![screen shot 2016-03-06 at 12 34 07 pm](https://cloud.githubusercontent.com/assets/4806884/13555808/f0748cec-e397-11e5-841f-c51a515e7c21.png)

**Comment by danbjoseph** [comment]
update to this. it's appearing in earned badges but the badge progress isn't showing anything. 
![screen shot 2016-03-09 at 8 27 14 am](https://cloud.githubusercontent.com/assets/4806884/13636612/c6c7f178-e5d0-11e5-951a-b0dc6550bf2c.png)
![screen shot 2016-03-09 at 8 27 23 am](https://cloud.githubusercontent.com/assets/4806884/13636615/c86a5ca0-e5d0-11e5-96ed-e1f2e2931068.png)

**Comment by bgirardot** [comment]
came here to say the same thing
![2016-03-15_20h37_01](https://cloud.githubusercontent.com/assets/265831/13791583/238226c8-eaee-11e5-84e5-79901848cb79.png)

**Comment by nbumbarger** [comment]
@danbjoseph @bgirardot 

Could you let me know whether it's possible that either of you hadn't submitted a changeset since contributing GPS traces?

Most of the metrics in the user API are derived from changesets as they are submitted, but a few of them, such as GPS traces and the planned HOT Tasking Manager integrations, depend on accessing  external APIs. Rather than continuously polling these APIs for each user in the system, the triggering event for an update is a changeset submission. More precisely, we update a user's GPS trace count when they submit a changeset and their existing trace count is more than 10 minutes out-of-date. We do this out of respect to the providers of these APIs, and to keep MM's own costs under control.

I see that your profiles have both been updated to show GPS traces, but the above should explain why you might see a lag the next time you submit some more. Keep up the good work!

**Comment by danbjoseph** [comment]
the badges earned and badge progress are still contradicting in my profile 
<img width="426" alt="screen shot 2016-05-12 at 2 44 01 pm" src="https://cloud.githubusercontent.com/assets/4806884/15226283/20aa0756-1850-11e6-8f21-edb1074a1001.png">
<img width="432" alt="screen shot 2016-05-12 at 2 44 05 pm" src="https://cloud.githubusercontent.com/assets/4806884/15226282/20a4c732-1850-11e6-8dc6-b3fd817f37e2.png">

**Comment by nbumbarger** [comment]
@danbjoseph I noticed that right after posting a response, it's fixed.

**Comment by danbjoseph** [comment]
👍
