### ISSUE TITLE
Badges failing to load for user 'piaco_dk'

### ISSUE THREAD

**Issue by harry-wood** [MissingMaps/missingmaps.github.io#177]
The badges system finds the user 'piaco_dk' : http://www.missingmaps.org/users/#/3442203

...but for this user the badges page fails to load logging the javascript error

`bundle.js:60991 Uncaught (in promise) TypeError: Cannot read property 'category' of undefined`

Something about [this user's editing history](http://www.openstreetmap.org/user/piaco_dk/history) trips it up.

**Comment by DylanMoriarty** [comment]
This appeared to be a bug with the script that checks what badges a user is most close to getting. 

[Piaco_dk](http://www.missingmaps.org/users/#/3442203) has more edits than any other user that we can tell, so it was wigging out that there wasn't a third badge he was closest to getting. We've added a failsafe for this case.

Also as a heads up, the data for this user is really huge. It may take a couple seconds for the page to load.

**Comment by piaco** [comment]
thanks for helping. -just one more little thing.  My water badge progress is not showing up. 
It disappeared a couple of days before the rest of them with only 12 km left to level 3. Could that one be the troublemaker.    /piaco_dk

**Comment by DylanMoriarty** [comment]
@piaco if you're talking about the white water rafting badge, it looks like it's there for you now 😄

**Comment by piaco** [comment]
Hi Dylan
Thanks. It's been there a couple of days now, -but I think I miss the badge
counting different countries I've been mapping in. as far as I remember I
was missing 2 countries to the next level. -and the consistency badge
doesn't make a countdown. Since my bagdebreakdown I've been missing 14 days
to next level -and I still do. Hope it can be fixed.  Have a nice day.
/piaco_dk

2016-05-20 20:25 GMT+02:00 Dylan <notifications@github.com>:
