### ISSUE TITLE
partners numbers not synced

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/missingmaps.github.io#216]
Seems that the banner is undercounting the contributions.

<img width="781" alt="screen shot 2016-06-15 at 7 48 28 am" src="https://cloud.githubusercontent.com/assets/1913857/16078570/ab66b320-32cd-11e6-91c6-e78eede43100.png">

<img width="1124" alt="screen shot 2016-06-15 at 7 48 35 am" src="https://cloud.githubusercontent.com/assets/1913857/16078569/ab65368a-32cd-11e6-8861-e1aed6b91023.png">

**Comment by DylanMoriarty** [comment]
@dalekunce I think this might just be an issue of what we labeled those as. Looking at the [all example](http://www.missingmaps.org/partners/all/), 57,749 matches what we have on the leaderboards under changesets.

My assumption is the mis-match in values might be happening because the total displayed under the Teams are a summation of buildings, roads (by #), and potentially other edits as well. 

Will look into this to verify, but I imagine changing the term to 'total edits' might be a good idea even if just initially.

**Comment by nbumbarger** [comment]
@dalekunce - We were using changeset submissions as the metric for contributions in several areas across the site. With the latest update, "Contributions" now refers to the sum of all additions and edits, both in the partner page and on the leaderboard.

There were some additional discrepancies in the road and building counts caused by not filtering for unique changesets, which have been rectified.
