### ISSUE TITLE
osm stats nav link and language picker odd behavior

### ISSUE THREAD

**Issue by danbjoseph** [MissingMaps/missingmaps.github.io#333]
- link to 'osm stats' will disappear from the dropdown on certain pages (user pages and leaderboard) 
- when on the 'osm stats' page using the language picker sends you to the 'about' page

**Comment by Omniscimus** [comment]
The second point is fixed in #344.

The first point is an issue with [users](https://github.com/MissingMaps/users/issues/41) and [leaderboards](https://github.com/MissingMaps/leaderboards/issues/15). The base code in this repository links to the separate users and leaderboards modules. The header on those modules is not consistent with the header in this repo.

**Comment by danbjoseph** [comment]
https://github.com/MissingMaps/users/commit/427fee66e19dcfefb2bb8d284ab77e7288478764#diff-6a1559e4b25e80b6a3b7c9c6b7d24db73177617ee8efbc935fae6fd8a59d1667 should update the header to match the main website.

there will still be issues across languages. not sure it's possible to resolve those without a complete overhaul.
