### ISSUE TITLE
Mapathon page - comments

### ISSUE THREAD

**Issue by pedrito1414** [MissingMaps/missingmaps.github.io#41]
Great addition to the web site with the mapathon pages. I have a couple of comments:

1. There's nothing to suggest that organisers contact their local HOT / OSM community to help support newbies / collaborate on the event. We have found this is fundamental to sustainable remotely organised mapathons that result in good quality data.

2. It's very Red Cross-centric. The language around Step 2: How can we help only references red cross / crescent and if you're organising in the UK, your support will come from MSF. In France, it would likely come from CartONG. Needs to be broader language.

Otherwise, amazing!

Pete

**Comment by danbjoseph** [comment]
@anjikoc can you please make edits based on these comments?

**Comment by pedrito1414** [comment]
@anjikoc let me know if need me to elaborate

**Comment by anjikoc** [comment]
Hi @pedrito1414 thanks for the great feedback and catching my oversight. How does the following sound:

Step 2: How we can help
We can provide your team with local or remote support to help coordinate and manage your event.  The Missing Maps Project is a global community of dedicated organizations and volunteers that may be available locally to support your event. Contact the Missing Maps Coordinator with your event date and location so that we can help you with following:
.......
.......
6.) Collaborate with your local Missing Maps partner organization – we can connect you with local Missing Maps partner organizations to help find mapping experts and handle translation services when available and appropriate.
